version: "3.9"

services:
  api:
    build: .
    image: agentic-sdlc-api:dev
    ports:
      - "${API_PORT:-8080}:8080"
    # Run in the same mode as pytest import style
    command: sh -c "python services/api/tools/db_init.py && uvicorn app:app --app-dir services/api --host 0.0.0.0 --port 8080 --reload"
    # Make root filesystem read-only; mount code read-only; tmpfs for /tmp
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - .:/app:ro
      - ./data:/app/data         # RW bind mount for artifacts
    tmpfs:
      - /tmp
      - /run
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=postgresql://agent:agent@db:5432/agentic
      - PLANS_ROOT=/app/data
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: agentic
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
    ports:
      - "5432:5432"
    # Hardening: read-only root, but keep writable data + runtime dirs via volume/tmpfs
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - pgdata:/var/lib/postgresql/data   # writable data
    tmpfs:
      - /run
      - /tmp
      - /var/run/postgresql               # socket dir
volumes:
  pgdata:
