openapi: 3.0.3
info:
  title: Notes Service
  version: "1.0.0"
servers:
  - url: /api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /notes:
    get:
      summary: List notes
      responses:
        "200":
          description: OK
    post:
      summary: Create note
      responses:
        "201":
          description: Created
  /notes/{id}:
    get:
      summary: Get note
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
    delete:
      summary: Delete note
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "204": { description: No Content }
