from typing import Protocol, List, Optional, Dict, Any

class NotesRepo(Protocol):
    def list(self) -> List[Dict[str, Any]]: ...
    def create(self, title: str, content: str) -> Dict[str, Any]: ...
    def get(self, id: str) -> Optional[Dict[str, Any]]: ...
    def update(self, id: str, title: str, content: str) -> Optional[Dict[str, Any]]: ...
    def delete(self, id: str) -> bool: ...
