openapi: 3.1.0
info:
  title: Agentic SDLC API
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: ok
  /requests:
    post:
      summary: Submit a new request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "200":
          description: request accepted
