openapi: 3.1.0
info:
  title: Test API
  version: 0.1.0
paths:
  /api/test:
    get:
      summary: List test
      responses:
        '200':
          description: OK
    post:
      summary: Create test
      responses:
        '201':
          description: Created
  /api/test/{id}:
    get:
      summary: Get test
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update test
      responses:
        '200':
          description: OK
    delete:
      summary: Delete test
      responses:
        '204':
          description: No Content
