openapi: 3.1.0
info:
  title: Add API
  version: 0.1.0
paths:
  /api/add:
    get:
      summary: List add
      responses:
        '200':
          description: OK
    post:
      summary: Create add
      responses:
        '201':
          description: Created
  /api/add/{id}:
    get:
      summary: Get add
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update add
      responses:
        '200':
          description: OK
    delete:
      summary: Delete add
      responses:
        '204':
          description: No Content
