openapi: 3.1.0
info:
  title: Ljk API
  version: 0.1.0
paths:
  /api/ljk:
    get:
      summary: List ljk
      responses:
        '200':
          description: OK
    post:
      summary: Create ljk
      responses:
        '201':
          description: Created
  /api/ljk/{id}:
    get:
      summary: Get ljk
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update ljk
      responses:
        '200':
          description: OK
    delete:
      summary: Delete ljk
      responses:
        '204':
          description: No Content
