openapi: 3.1.0
info:
  title: Create API
  version: 0.1.0
paths:
  /api/create:
    get:
      summary: List create
      responses:
        '200':
          description: OK
    post:
      summary: Create create
      responses:
        '201':
          description: Created
  /api/create/{id}:
    get:
      summary: Get create
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update create
      responses:
        '200':
          description: OK
    delete:
      summary: Delete create
      responses:
        '204':
          description: No Content
