openapi: 3.1.0
info:
  title: Project API
  version: 0.1.0
paths:
  /api/project:
    get:
      summary: List project
      responses:
        '200':
          description: OK
    post:
      summary: Create project
      responses:
        '201':
          description: Created
  /api/project/{id}:
    get:
      summary: Get project
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update project
      responses:
        '200':
          description: OK
    delete:
      summary: Delete project
      responses:
        '204':
          description: No Content
