openapi: 3.1.0
info:
  title: Safsaq API
  version: 0.1.0
paths:
  /api/safsaq:
    get:
      summary: List safsaq
      responses:
        '200':
          description: OK
    post:
      summary: Create safsaq
      responses:
        '201':
          description: Created
  /api/safsaq/{id}:
    get:
      summary: Get safsaq
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update safsaq
      responses:
        '200':
          description: OK
    delete:
      summary: Delete safsaq
      responses:
        '204':
          description: No Content
