openapi: 3.1.0
info:
  title: Resource API
  version: 0.1.0
paths:
  /api/resource:
    get:
      summary: List resource
      responses:
        '200':
          description: OK
    post:
      summary: Create resource
      responses:
        '201':
          description: Created
  /api/resource/{id}:
    get:
      summary: Get resource
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update resource
      responses:
        '200':
          description: OK
    delete:
      summary: Delete resource
      responses:
        '204':
          description: No Content
