openapi: 3.1.0
info:
  title: Build API
  version: 0.1.0
paths:
  /api/build:
    get:
      summary: List build
      responses:
        '200':
          description: OK
    post:
      summary: Create build
      responses:
        '201':
          description: Created
  /api/build/{id}:
    get:
      summary: Get build
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update build
      responses:
        '200':
          description: OK
    delete:
      summary: Delete build
      responses:
        '204':
          description: No Content
