openapi: 3.0.0
info:
  title: Notes Service
  version: "1.0.0"
paths:
  /api/notes:
    get:
      summary: List notes
      responses:
        '200':
          description: OK
    post:
      summary: Create note
      responses:
        '201':
          description: Created
  /api/notes/{id}:
    get:
      summary: Get note
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Delete note
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
