openapi: 3.1.0
info:
  title: Fdas API
  version: 0.1.0
paths:
  /api/fdas:
    get:
      summary: List fdas
      responses:
        '200':
          description: OK
    post:
      summary: Create fda
      responses:
        '201':
          description: Created
  /api/fdas/{id}:
    get:
      summary: Get fda
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update fda
      responses:
        '200':
          description: OK
    delete:
      summary: Delete fda
      responses:
        '204':
          description: No Content
