openapi: 3.1.0
info:
  title: Sdaffasd API
  version: 0.1.0
paths:
  /api/sdaffasd:
    get:
      summary: List sdaffasd
      responses:
        '200':
          description: OK
    post:
      summary: Create sdaffasd
      responses:
        '201':
          description: Created
  /api/sdaffasd/{id}:
    get:
      summary: Get sdaffasd
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update sdaffasd
      responses:
        '200':
          description: OK
    delete:
      summary: Delete sdaffasd
      responses:
        '204':
          description: No Content
