name: CI
run-name: "PR #${{ github.event.pull_request.number }} • ${{ github.event.pull_request.title || github.ref_name }}"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: API deps
        run: |
          python -m pip install --upgrade pip
          pip install -r orchestrator/requirements.txt
          pip install -r services/api/requirements.txt
          pip install -r tools/requirements.txt

      - name: Run orchestrator summary
        run: |
          python orchestrator/main.py
          
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Test
        run: PYTHONPATH=${GITHUB_WORKSPACE} coverage run -m pytest -q
        
      - name: Unit tests (API)
        working-directory: services/api
        run: |
          coverage run -m pytest -q
          coverage xml -o ../../reports/coverage.xml
          coverage report -m

      - name: QA gate (coverage threshold)
        run: |
          python tools/qa_agent.py --strict --xml reports/coverage.xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: reports/coverage.xml
          docker-build:
      - uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -t agentic-sdlc-api:ci .
  semgrep:
    name: Semgrep (SAST + Secrets)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install semgrep==1.74.0
      - name: Scan
        run: |
          semgrep --config p/default --config p/secrets --error \
                  --exclude .venv --exclude node_modules --exclude reports
